version: '3.2'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  worker:
    container_name: worker
    build:
      context: backend
      dockerfile: Dockerfile
    command: celery --app app.tasks worker --loglevel=DEBUG -Q main-queue -c 1

  flower:
    container_name: flower
    image: mher/flower
    command: celery flower --broker=redis://redis:6379/0 --port=5555
    ports:  
        - 5555:5555
    depends_on:
      - "redis"
    environment:
    - CELERY_BROKER_URL=redis://redis:6379/0

  backend:
    container_name: backend
    ports:
      - 8888:8888
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    volumes:
      - ./backend:/app/
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'mysql+pymysql://root:example@mysql:3306/testdb'
    depends_on:
      - "mysql"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    entrypoint: bash -c "yarn && yarn start"
    volumes:
      - ./frontend/src:/app/src
      - type: bind
        source: ./frontend/package.json
        target: /app/package.json
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000/api/v1
      - REACT_APP_TIME_OUT=25000
      - REACT_APP_IMAGE_URL=https://vn-authoring-system-content-upload-s3.s3.ap-northeast-1.amazonaws.com/asset_imgs/
    ports:
      - 3000:3000
    depends_on:
      - backend
    restart: always

volumes:
  mysql-data:
  mongodb-data: